version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5001:80' # Map host port 5000 to container port 80
    volumes:
      - ./server/src:/server/src

  client:
    build: ./client
    ports:
      - '3000:3000' # Map host port 5000 to container port 80
    volumes:
      - ./client:/client
